blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/PharmicaUK/Pharmica.AssetGen/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/PharmicaUK/Pharmica.AssetGen#readme
    about: Read the documentation and FAQ
